//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADO_TEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class it_is_me
    {
        public int ID_I { get; set; }
        public string First_name { get; set; }
        public string Second_name { get; set; }
        public string Patronymic { get; set; }
        public byte[] Photo { get; set; }
        public int ID_how_to_contact_me { get; set; }
        public int ID_reputation { get; set; }
    }
}
